name: get
on: 
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: Ubuntu-20.04

    steps:
    - name: Download
      run: |
        mkdir ./bingpic
        cd ./bingpic
        curl https://api.cyfan.top/bing?day=0 -o bing.jpg   
        curl https://api.cyfan.top/bing?day=1 -o 2.jpg   
        curl https://api.cyfan.top/bing?day=2 -o 3.jpg
        curl https://api.cyfan.top/bing?day=3 -o 4.jpg
        curl https://api.cyfan.top/bing?day=4 -o 5.jpg
        curl https://api.cyfan.top/bing?day=5 -o 6.jpg
        curl https://api.cyfan.top/bing?day=6 -o 7.jpg
        curl https://api.cyfan.top/bing?day=7 -o 8.jpg
        curl https://api.cyfan.top/binginfo?day=0 -o bing.js  
        curl https://api.cyfan.top/binginfo?day=1 -o 2.js
        curl https://api.cyfan.top/binginfo?day=2 -o 3.js
        curl https://api.cyfan.top/binginfo?day=3 -o 4.js
        curl https://api.cyfan.top/binginfo?day=4 -o 5.js
        curl https://api.cyfan.top/binginfo?day=5 -o 6.js
        curl https://api.cyfan.top/binginfo?day=6 -o 7.js
        curl https://api.cyfan.top/binginfo?day=7 -o 8.js
        cd ..
        mkdir ./one-note
        cd ./one-note
        curl https://api.cyfan.top/dujitang -o djt.js
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
