name: get
on: 
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        mkdir ./bingpic
        cd ./bingpic
        curl https://pan.cyfan.top/api/bing/bing.php -o bing.jpg   
        curl https://pan.cyfan.top/api/bing/2.php -o 2.jpg   
        curl https://pan.cyfan.top/api/bing/3.php -o 3.jpg
        curl https://pan.cyfan.top/api/bing/4.php -o 4.jpg
        curl https://pan.cyfan.top/api/bing/5.php -o 5.jpg
        curl https://pan.cyfan.top/api/bing/6.php -o 6.jpg
        curl https://pan.cyfan.top/api/bing/7.php -o 7.jpg
        curl https://pan.cyfan.top/api/bing/8.php -o 8.jpg
        curl https://pan.cyfan.top/api/bing/bingc.php -o bing.js  
        curl https://pan.cyfan.top/api/bing/2c.php -o 2.js
        curl https://pan.cyfan.top/api/bing/3c.php -o 3.js
        curl https://pan.cyfan.top/api/bing/4c.php -o 4.js
        curl https://pan.cyfan.top/api/bing/5c.php -o 5.js
        curl https://pan.cyfan.top/api/bing/6c.php -o 6.js
        curl https://pan.cyfan.top/api/bing/7c.php -o 7.js
        curl https://pan.cyfan.top/api/bing/8c.php -o 8.js
        cd ..
        mkdir ./one-note
        cd ./one-note
        curl https://pan.cyfan.top/api/yiyan/api.php -o yiyan.js
        curl https://pan.cyfan.top/api/djt/api.php -o djt.js
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
